### ISSUE TITLE
re-evaluate testing different combinations of C-stdlibs, C++-stdlibs and C++-rtlibs

### ISSUE THREAD

**Issue by usf-tfawcett** [seqan/seqan#2050]
cmake flags = -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/where/i/am/going

The CMakeError.log file contains:
> Performing C++ SOURCE FILE Test CXX14_BUILTIN failed with the following output:
> Change Dir: /shares/apps/seqan/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/bin/gmake" "cmTC_31c4b/fast"
> /usr/bin/gmake -f CMakeFiles/cmTC_31c4b.dir/build.make CMakeFiles/cmTC_31c4b.dir/build
> gmake[1]: Entering directory `/shares/apps/seqan/build/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_31c4b.dir/src.cxx.o
> /apps/intel/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc     -DCXX14_BUILTIN   -o CMakeFiles/cmTC_31c4b.dir/src.cxx.o -c /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx
> /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx(2): error: #error directive: NOCXX14
>       #error NOCXX14
>        ^
> 
> compilation aborted for /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx (code 2)
> gmake[1]: *** [CMakeFiles/cmTC_31c4b.dir/src.cxx.o] Error 2
> gmake[1]: Leaving directory `/shares/apps/seqan/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_31c4b/fast] Error 2
> 
> Source file was:
> #if !defined(__cplusplus) || (__cplusplus < 201300L)
>     #error NOCXX14
>     #endif
>     int main() {}
> Performing C++ SOURCE FILE Test CXX14_FLAG failed with the following output:
> Change Dir: /shares/apps/seqan/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/bin/gmake" "cmTC_46dbd/fast"
> /usr/bin/gmake -f CMakeFiles/cmTC_46dbd.dir/build.make CMakeFiles/cmTC_46dbd.dir/build
> gmake[1]: Entering directory `/shares/apps/seqan/build/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_46dbd.dir/src.cxx.o
> /apps/intel/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc     -std=c++14 -DCXX14_FLAG   -o CMakeFiles/cmTC_46dbd.dir/src.cxx.o -c /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx
> /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx(2): error: #error directive: NOCXX14
>       #error NOCXX14
>        ^
> 
> compilation aborted for /shares/apps/seqan/build/CMakeFiles/CMakeTmp/src.cxx (code 2)
> gmake[1]: *** [CMakeFiles/cmTC_46dbd.dir/src.cxx.o] Error 2
> gmake[1]: Leaving directory `/shares/apps/seqan/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_46dbd/fast] Error 2
> 
> Source file was:
> #if !defined(__cplusplus) || (__cplusplus < 201300L)
>     #error NOCXX14
>     #endif
>     int main() {}

If I compile `int main(){}` with icpc --std=c++14, i get no compile errors

I have no issues using gcc 6.2.0, but would like to use Intel for obvious reasons.  Any help would be greately appreciated.

**Comment by usf-tfawcett** [comment]
OK, so...  I see now that this is expected as the test does indeed fail.  However, Intel 17.0 supports (at least some) of c++14.  If Intel 17.0 not supported?  We have not installed 16.0 on our cluster, just 15.0 and 17.0.

**Comment by h-2** [comment]
@marehr Any news on this? We have 17 now, as well, don't we?

**Comment by marehr** [comment]
Hi @usf-tfawcett,

I'm terribly sorry that I somehow missed your bug report. First of all, great to hear that someone uses the Intel Compiler that took some time to get it working. And yes, we do support the Intel Compiler 17.

I tried to execute cmake on our internal buildsystem and on an external app like [lambda](/seqan/lambda) and it worked in both cases with 17.0.1 and 17.0.2.

I also compiled our test for the c++-14 support with our Installation of the Intel Compiler and it did work.

```c++
// icpc -std=c++14 cpp14_check.cpp
#if !defined(__cplusplus) || (__cplusplus < 201300L)
#error NOCXX14
#endif
int main() {}
```

* Which version of the Intel Compiler do you have? `icpc --version`
* What is `icpc -dM -E - < /dev/null`? [It will show all predefined macros.](http://stackoverflow.com/a/2224357)
* Maybe you could attach the whole build log?
* Maybe give me access to the code you want to compile? Or your exact steps what you did, i.e. what did you clone, which version/revision of seqan did you use and so on.

Thank you!

**Comment by usf-tfawcett** [comment]
Ended up being my error, BUT worth documenting for building with Intel 
compilers.

I thought I had been adding gcc 6.2.0 to the environment for Standard 
Libs to work with the Intel 2017 compiler.  However, I just realized 
(through testing to get you cmake output files) that this was not the case.

The problem stems from Intel compilers not shipping with their own 
copies of Standard Libs, so the Intel compiler uses whatever is 
available in various paths which would include whatever gcc is currently 
using.  Since I had not setup the gcc 6.2.0 environment, the Intel 2017 
compilers were using standard libs from the system gcc which for RH6.8 
(for us at least) is gcc 4.4.7 which is NOT c++14 compliant (with 
copyright 2010).

Thus, the real requirement is Intel 2017 + gcc 4.9 (5.0 recommended), 
not Intel 2017 OR gcc 4.9 (5.0 recommended).  Yes, compiling on a single 
system with no optional versions of gcc being available would have 
likely forced this requirement.  But most cluster installs use Linux 
modules to maintain separate environments.

It would be nice to see details related to this in the install/build 
documentation.  I should have (and though I did) already take care of 
this, but I see the potential confusion now. For me, just one missing 
module line and it does not build.

Thank you!

------------------------------------------------------------------------



*From:* Marcel
*Sent:* Tuesday, April 18, 2017 10:20AM
*To:* Seqan/seqan
*Cc:* Usf-tfawcett, Mention
*Subject:* Re: [seqan/seqan] cmake fails to detect c++14 standard flag 
OK with Intel 2017 (17.0) (#2050)

**Comment by marehr** [comment]
We can incorporate this in our documentation. Your solution is unfortunately to custom tailored for a cluster. So it would be better to give our users a more general hint:

Maybe something like this:

> **IMPORTANT:**
> The Intel Compiler does not ship a c++ standard library on its own and will use the one pre-installed on the system (i.e., the one from g++). This can be a problem [especially for cluster users through the use of a module system], if the standard library by a default g++ installation is to old.
>
> Please check with the following command which g++ version is being used and make sure it matches the supported gcc versions.
> > `icpc -v` 
> > icpc version 17.0.2 (gcc version 5.4.0 compatibility)
>
> If you have multiple g++ installations, you can choose the standard library by
> `icpc -gxx-name=g++-5.3.0 -gcc-name=gcc-5.3.0 …`
>
> You may have to add the path of the library to `$LD_LIBRARY_PATH` for the linker.

Have you any suggestions on the wording?

**Comment by usf-tfawcett** [comment]
I think that would be great!  Thank you!



*Timothy J. Fawcett, Ph.D.*
Computational Scientist/Research Professor
University of South Florida - Information Technology
Research Computing
4202 E. Fowler Ave, SVC 5024
Tampa, FL 33620
Email: tfawcett@usf.edu <mailto:tfawcett@usf.edu> | Tel: (813) 974-6141

------------------------------------------------------------------------



*From:* Marcel
*Sent:* Wednesday, April 19, 2017 2:54PM
*To:* Seqan/seqan
*Cc:* Usf-tfawcett, Mention
*Subject:* Re: [seqan/seqan] cmake fails to detect c++14 standard flag 
OK with Intel 2017 (17.0) (#2050)

**Comment by h-2** [comment]
I thought about documenting the standard library requirements separately, as well, because there are other pitfalls, e.g. libc++ (clang) vs libstdc++ (gcc)  and also OS (on Linux clang uses libstdc++ by default, on BSD and Mac it uses libc++). To make it even worse, there are also completely operating systems specific c-standard-libraries, and since modern c++ standards incorporate modern c-standards, these are also relevant. Then there are run-time

|         | C STD lib | C++ STD lib | C++ RT |
|--------|--------------|------------------|------------|
|GNU | `glibc`       | `libstdc++`   | `libsupc++` |
|LLVM |                | `libc++`        | `libcxxabi` |
|BSD| BSD `libc` |                      | `libcxxrt`|
|musl| musl `libc` |                     |                |

Now, depending on platform and compiler different combinations of these are possible. 
 * on GNU systems, including Linux, all compilers use the GNU libs by default. Clang can however use the LLVM libs optionally, and also the musl-libc.
 * On OSX the clang compiler uses the LLVM libs by default (and the BSD libc). GCC on OSX however uses the GNU libs shipped with GCC. Intel on OSX (`icl++`, not `icpc`) uses the LLVM libs.
 * On BSD all compilers use BSD libc, clang uses libc++ and libcxxrt; and GCC again uses the GNU libs that it ships with. Intel on FreeBSD is like intel on OSX, except it also uses libcxxrt AFAICT (but intel on FreeBSD is beta anyway).
 * Certain LLVM projects like Emscripten, always use musl libc, independent of other lib choices.

What makes it even more confusing, is that certain version of GNU's libstdc++ are support certain ISO standards, but only with GCC and not with Clang (because they depend on some GCC hackery). I think that beginning with GCC-5 this has stopped, though. And, unluckily libstdc++ doesn't provide a version macro that indicates to which GCC version it belongs :cry: 

Maybe should create a test matrix that covers standard libs, as well, but only for nightlies and weeklies, not CI.

**Comment by rrahn** [comment]
I leave this issue open for the last post by @h-2.
But we might move it to another Milestone.

**Comment by h-2** [comment]
moved to 3.0
