### ISSUE TITLE
failure to build from source with GCC6

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#1342]
Hello from Debian-med,

GCC 6 is likely to be the default compiler for the upcoming Debian "stretch" release. While GCC 6 has not been released, Debian has begun the search for software that will need updating.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811841

You may be able to find out more about this issue at https://gcc.gnu.org/gcc-6/changes.html

Example error:

```
> /<<BUILDDIR>>/seqan-1.4.1+dfsg/core/include/seqan/basic/debug_test_system.h: In instantiation of 'bool seqan::ClassTest::testTrue(const char*, int, const T&, const char*, const char*, ...) [with T = std::basic_ifstream<char>]':
> /<<BUILDDIR>>/seqan-1.4.1+dfsg/core/include/seqan/basic/debug_test_system.h:1410:20:   required from 'bool seqan::ClassTest::testTrue(const char*, int, const T&, const char*) [with T = std::basic_ifstream<char>]'
> /<<BUILDDIR>>/seqan-1.4.1+dfsg/core/tests/store/test_store_io.h:435:9:   required from 'void SEQAN_TEST_test_store_io_sam() [with bool speed_up_dummy_to_prevent_compilation_of_unused_tests_ = true]'
> /<<BUILDDIR>>/seqan-1.4.1+dfsg/core/tests/store/test_store.cpp:60:5:   required from here
> /<<BUILDDIR>>/seqan-1.4.1+dfsg/core/include/seqan/basic/debug_test_system.h:1362:64: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'const std::basic_ifstream<char>')
>          std::cerr << file << ":" << line << " Assertion failed : "
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                    << expression_ << " should be true but was " << (value_);
>                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

**Comment by rrahn** [comment]
Hey, thanks for pointing to it.
The seqan version seems a little bit old, though :confused:

**Comment by mr-c** [comment]
We are working on the packages for v2.0.1; looks like we had build problems with v2.0 https://lists.debian.org/debian-med/2015/07/msg00045.html

**Comment by h-2** [comment]
I will add gcc-6 to our build matrix. You might want to wait for seqan-2.0.2 and/or seqan-2.1.0 which are to be released in the next two weeks, though. There have been fixes, also build related, that should make deploying the package a lot easier.

**Comment by h-2** [comment]
I have just built the current master branch with gcc-6. There were no errors, only some new warnings that will be fixed prior to the next release, please see #1345 

@mr-c can you keep us up to date on the debian packages in #1343 ? Thanks a lot!
