### ISSUE TITLE
Commit b09e87e0 causes link error "undefined reference to `pthread_create'" on Linux

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2268]
On Linux, SeqAn seems to need libpthread for multithreaded BAM file I/O (at least).  But since commit b09e87e0 (I think; I haven't tried git bisect to verify), using any SeqAn code that needs libpthread leads to the linker error "undefined reference to `pthread_create'".

TTBOMK, the reason is: Prior to commit b09e87e0, libpthread was included by appending `pthread` to `SEQAN_LIBRARIES` in CMakeLists.txt, which has the effect of *appending* `-lpthread` to the command line sent to the linker.  Since that commit, instead of appending to `SEQAN_LIBRARIES`, some linker options including `-lpthread` are appended to `CMAKE_EXE_LINKER_FLAGS`, which has the effect of *prepending* `-lpthread` to the command line sent to the linker -- and since the linker (on Linux anyway) only extracts library object code for symbols referenced by object files *that appeared earlier on the linker command line*, this means that `pthread_create` is never found, causing the link failure.  (FWIW this linker behaviour seems crazy to me.  But perhaps there's some justification if you dig deep enough...)

What puzzles me is why this build error apparently hasn't caused problems with SeqAn's own CI tests.  I'm running a very standard Ubuntu Linux 4.8.0-59-generic with g++ 6.3.0, so I don't think it's some peculiarity of my system.  I'm on the `develop` branch.

Note that prior to this commit, the "new" behaviour of using `CMAKE_EXE_LINKER_FLAGS` instead of `SEQAN_LIBRARIES` to include libpthread could already occur under other conditions (when building statically, it would seem), and it was possibly broken for that also.

**Workaround:** Manually specify `SEQAN_LIBRARIES` when running CMake.  For me this amounted to adding `-DSEQAN_LIBRARIES="pthread;rt;/usr/lib/x86_64-linux-gnu/libz.so"` to the CMake command line.

**Comment by h-2** [comment]
Are you building statically or dynamically? Are you referring to SeqAn's internal apps/tests or your own application?

Linking pthread on Linux is severely broken, but we want through a lot of trouble to get things right the last time. We are testing on Debian stable, and also an ancient CentOS version. Furthermore the integration and app tests pass on current Debian via their infrastructure and on current Fedora build machines (with the exception of #2272). 

So could you please provide us with more details of your current setup?

Thanks!

**Comment by wtwhite** [comment]
Hi, thanks for getting back to me.

I'm referring to building a simple application of my own, using a few-days-old `develop` branch of SeqAn with the 2-line fix in https://github.com/seqan/seqan/pull/2266 on top of it.  I'm using CMake on a reasonably recent Ubuntu inside a VirtualBox on Windows:

```
wtwhite@wtwhite-VirtualBox:~$ uname -a
Linux wtwhite-VirtualBox 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
wtwhite@wtwhite-VirtualBox:~$ g++ --version
g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

wtwhite@wtwhite-VirtualBox:~$ cmake --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

It sounds like you guys are having no problems with builds so it could certainly be something I'm doing, but I can't think what...  For comparison, there were no link problems when I was using the `libseqan2-dev` package version 2.3.1+dfsg-3ubuntu1 installed by `apt-get`.

I don't recall where I read about the way the linker looks up symbols unfortunately, but I definitely remember banging my head against this problem years ago.

I've attached a MWE, including CMakeLists.txt, that reproduces the link error for me if I have commit f3bef57 checked out under `$SEQAN` and run `mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$SEQAN/util/cmake -DSEQAN_INCLUDE_PATH=$SEQAN/include .. && make VERBOSE=1`.  The output I get from this is:

```
wtwhite@wtwhite-VirtualBox:~/win/repro_seqan_pthread_link_error$ mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$SEQAN/util/cmake -DSEQAN_INCLUDE_PATH=$SEQAN/include .. && make VERBOSE=1
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake build type: Release
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Performing Test CXX14_BUILTIN
-- Performing Test CXX14_BUILTIN - Success
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Found Seqan: /home/wtwhite/win/seqan/include (found version "2.4.0")
SEQAN_LIBRARIES=<rt;/usr/lib/x86_64-linux-gnu/libz.so>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wtwhite/win/repro_seqan_pthread_link_error/build
make: Warning: File 'Makefile' has modification time 1,4 s in the future
/usr/bin/cmake -H/home/wtwhite/win/repro_seqan_pthread_link_error -B/home/wtwhite/win/repro_seqan_pthread_link_error/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles /home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 1,2 s in the future
make -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/depend
make[2]: Entering directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
make[2]: Warning: File 'CMakeFiles/x.dir/flags.make' has modification time 1,2 s in the future
cd /home/wtwhite/win/repro_seqan_pthread_link_error/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/wtwhite/win/repro_seqan_pthread_link_error /home/wtwhite/win/repro_seqan_pthread_link_error /home/wtwhite/win/repro_seqan_pthread_link_error/build /home/wtwhite/win/repro_seqan_pthread_link_error/build /home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/DependInfo.cmake --color=
Dependee "/home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/DependInfo.cmake" is newer than depender "/home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/depend.internal".
Dependee "/home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/wtwhite/win/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/depend.internal".
Scanning dependencies of target x
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Leaving directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
make -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/build
make[2]: Entering directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
make[2]: Warning: File 'CMakeFiles/x.dir/flags.make' has modification time 0,28 s in the future
[ 50%] Building CXX object CMakeFiles/x.dir/x.cpp.o
/usr/bin/c++   -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_ZLIB=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/wtwhite/win/seqan/include  -O3 -DNDEBUG   -o CMakeFiles/x.dir/x.cpp.o -c /home/wtwhite/win/repro_seqan_pthread_link_error/x.cpp
[100%] Linking CXX executable x
/usr/bin/cmake -E cmake_link_script CMakeFiles/x.dir/link.txt --verbose=1
/usr/bin/c++     -O3 -DNDEBUG   -Wl,--whole-archive -lpthread -Wl,--no-whole-archive CMakeFiles/x.dir/x.cpp.o  -o x -rdynamic -lrt -lz 
CMakeFiles/x.dir/x.cpp.o: In function `seqan::basic_unbgzf_streambuf<char, std::char_traits<char>, std::allocator<char>, char, std::allocator<char> >::basic_unbgzf_streambuf(std::istream&, unsigned long, unsigned long)':
x.cpp:(.text._ZN5seqan22basic_unbgzf_streambufIcSt11char_traitsIcESaIcEcS3_EC2ERSimm[_ZN5seqan22basic_unbgzf_streambufIcSt11char_traitsIcESaIcEcS3_EC5ERSimm]+0x66b): undefined reference to `pthread_create'
CMakeFiles/x.dir/x.cpp.o: In function `seqan::basic_bgzf_streambuf<char, std::char_traits<char>, std::allocator<char>, char, std::allocator<char> >::basic_bgzf_streambuf(std::ostream&, unsigned long, unsigned long)':
x.cpp:(.text._ZN5seqan20basic_bgzf_streambufIcSt11char_traitsIcESaIcEcS3_EC2ERSomm[_ZN5seqan20basic_bgzf_streambufIcSt11char_traitsIcESaIcEcS3_EC5ERSomm]+0x80e): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/x.dir/build.make:95: recipe for target 'x' failed
make[2]: *** [x] Error 1
make[2]: Leaving directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/x.dir/all' failed
make[1]: *** [CMakeFiles/x.dir/all] Error 2
make[1]: Leaving directory '/home/wtwhite/win/repro_seqan_pthread_link_error/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**MWE:** [repro_seqan_pthread_link_error.zip](https://github.com/seqan/seqan/files/1700518/repro_seqan_pthread_link_error.zip)

I hope the above helps, if not please let me know!

**Comment by h-2** [comment]
I have had no problems building the above example with seqan-2.4.0:
```
h4nn3s@larix .../repro_seqan_pthread_link_error/build % cmake ../
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake build type: Release
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Performing Test CXX14_BUILTIN
-- Performing Test CXX14_BUILTIN - Failed
-- Performing Test CXX14_FLAG
-- Performing Test CXX14_FLAG - Success
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Found Seqan: /tmp/seqan-root/include (found version "2.4.0")
SEQAN_LIBRARIES=<rt;/usr/lib/x86_64-linux-gnu/libz.so>
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/repro_seqan_pthread_link_error/build

h4nn3s@larix .../repro_seqan_pthread_link_error/build % make VERBOSE=1
/usr/bin/cmake -H/tmp/repro_seqan_pthread_link_error -B/tmp/repro_seqan_pthread_link_error/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/repro_seqan_pthread_link_error/build/CMakeFiles /tmp/repro_seqan_pthread_link_error/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/tmp/repro_seqan_pthread_link_error/build'
make -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/depend
make[2]: Entering directory '/tmp/repro_seqan_pthread_link_error/build'
cd /tmp/repro_seqan_pthread_link_error/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/repro_seqan_pthread_link_error /tmp/repro_seqan_pthread_link_error /tmp/repro_seqan_pthread_link_error/build /tmp/repro_seqan_pthread_link_error/build /tmp/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/DependInfo.cmake --color=
Dependee "/tmp/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/DependInfo.cmake" is newer than depender "/tmp/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/depend.internal".
Dependee "/tmp/repro_seqan_pthread_link_error/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/repro_seqan_pthread_link_error/build/CMakeFiles/x.dir/depend.internal".
Scanning dependencies of target x
make[2]: Leaving directory '/tmp/repro_seqan_pthread_link_error/build'
make -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/build
make[2]: Entering directory '/tmp/repro_seqan_pthread_link_error/build'
/usr/bin/cmake -E cmake_progress_report /tmp/repro_seqan_pthread_link_error/build/CMakeFiles 1
[100%] Building CXX object CMakeFiles/x.dir/x.cpp.o
/usr/bin/c++   -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_ZLIB=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++14  -O3 -DNDEBUG -I/tmp/seqan-root/include    -o CMakeFiles/x.dir/x.cpp.o -c /tmp/repro_seqan_pthread_link_error/x.cpp
Linking CXX executable x
/usr/bin/cmake -E cmake_link_script CMakeFiles/x.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++14  -O3 -DNDEBUG    -Wl,--whole-archive -lpthread -Wl,--no-whole-archive CMakeFiles/x.dir/x.cpp.o  -o x -rdynamic -lrt -lz 
make[2]: Leaving directory '/tmp/repro_seqan_pthread_link_error/build'
/usr/bin/cmake -E cmake_progress_report /tmp/repro_seqan_pthread_link_error/build/CMakeFiles  1
[100%] Built target x
make[1]: Leaving directory '/tmp/repro_seqan_pthread_link_error/build'
/usr/bin/cmake -E cmake_progress_start /tmp/repro_seqan_pthread_link_error/build/CMakeFiles 0
make VERBOSE=1  15,71s user 0,43s system 98% cpu 16,314 total

h4nn3s@larix .../repro_seqan_pthread_link_error/build % ./x < /tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
@SQ     SN:chr1 LN:249250621
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
@SQ     SN:chr4 LN:191154276
@SQ     SN:chr5 LN:180915260
@SQ     SN:chr6 LN:171115067
@SQ     SN:chr7 LN:159138663
@SQ     SN:chr8 LN:146364022
@SQ     SN:chr9 LN:141213431
@SQ     SN:chr10        LN:135534747
@SQ     SN:chr11        LN:135006516
@SQ     SN:chr12        LN:133851895
@SQ     SN:chr13        LN:115169878
@SQ     SN:chr14        LN:107349540
@SQ     SN:chr15        LN:102531392
@SQ     SN:chr16        LN:90354753
@SQ     SN:chr17        LN:81195210
@SQ     SN:chr18        LN:78077248
@SQ     SN:chr19        LN:59128983
@SQ     SN:chr20        LN:63025520
@SQ     SN:chr21        LN:48129895
@SQ     SN:chr22        LN:51304566
@SQ     SN:chrM LN:16571
@SQ     SN:chrX LN:155270560
```

This is on debian oldstable:
```
h4nn3s@larix .../repro_seqan_pthread_link_error/build % uname -a
Linux larix 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
h4nn3s@larix .../repro_seqan_pthread_link_error/build % cat /etc/debian_version
8.10
```

But I will also try on Ubuntu if I find an install here somewhere.

**Comment by h-2** [comment]
Can you check with seqan-2.4.0 whether just replacing ` CMAKE_EXE_LINKER_FLAGS` with `SEQAN_LIBRARIES` in l.310 of seqan-config.cmake fixes the problem for you? It does work here and I could change it if it makes it work for you.

[note that is is not the same as specifying `-DSEQAN_LIBRARIES="pthread...` as you wrote above, because we have this whole-archive voodoo additionally]

**Comment by wtwhite** [comment]
Thanks for looking at this.

Building with branch `seqan-v2.4.0-rc2` checked out gives the same error message, I'm afraid.  Changing (both instances of) `CMAKE_EXE_LINKER_FLAGS` to `SEQAN_LIBRARIES` on line 310 of seqan-config.cmake *does* result in a successful build, so that's good news, but I'm a bit concerned by the whole-archive cruft now appearing there, which will probably break anything expecting to see only actual library names -- the relevant line of output from my `cmake` is:

```
SEQAN_LIBRARIES=<rt -Wl,--whole-archive -lpthread -Wl,--no-whole-archive;/usr/lib/x86_64-linux-gnu/libz.so>
```
(I'm not too familiar with CMake, but it looks to me like `rt` is separated from `-Wl,--whole-archive...` by a space, whereas other "list items" are semicolon-delimited...  Looks a bit fragile.)

One more thing: I compared the (successful) linker command line from your `make VERBOSE=1` log with my (unsuccessful) one, and the only difference I could spot was that your line additionally contained `-std=c++14`.  I tried running your linker command directly, but it gave me the same linker error message as always, so leaving out `-std=c++14` doesn't seem to be what's causing the problem on my machine.

**Comment by wtwhite** [comment]
I've found the problem.  It's somehow caused by "clock skew" -- the phenomenon where a filesystem reports modification times "in the future", which can confuse `make`.

So far, I've been building in a directory that is actually mounted into the Linux VM guest from the Windows host, whose system clock is running 0.5-2s ahead of the Linux guest, and this produces clock skew warnings (visible in the logging output of `make VERBOSE=1` I gave in my second message on this thread) and the link error.  But when I copied the MWE files to a locally mounted filesystem and tried building -- voila!  No problems!

What still baffles me is how the build *succeeds* despite clock skew *when `-lpthread` appears after the main object file on the linker command line*, as it did in earlier SeqAn releases...

While this now appears not to be a bug per se, I expect that many SeqAn users develop in conditions where clock skew can occur -- not just inside a VM, but any network-mounted filesystem is vulnerable.  So I would appreciate still treating this as something to fix.

**Comment by h-2** [comment]
> What still baffles me is how the build succeeds despite clock skew when -lpthread appears after the main object file on the linker command line, as it did in earlier SeqAn releases...

The entire build and linkage process on unix is broken IMHO. It's one of the reasons people now bundle trimmed down operating systems with their binaries (Docker...).

>While this now appears not to be a bug per se, I expect that many SeqAn users develop in conditions where clock skew can occur -- not just inside a VM, but any network-mounted filesystem is vulnerable. So I would appreciate still treating this as something to fix.

I agree.

> but I'm a bit concerned by the whole-archive cruft now appearing there, which will probably break anything expecting to see only actual library names

Yeah, I don't like it either, that's exactly why I moved it to the linker arguments – however I don't think we have any other options here. We need whole-archive in case of static builds, because modern C++ uses pthread functionality that Debian stripped from their pthread build files :expressionless:
And we don't know yet if the build will be static at the point the module is loaded (which is why it was changed in the first place).
So I will make a PR that changes `CMAKE_EXE_LINKER_FLAGS` to `SEQAN_LIBRARIES`.

P.S: regarding your comment inside the file:
```cmake
# WTJW 9/1/2018: Ubuntu (at least) puts seqan-config.cmake into /usr/share/cmake, which is *NOT* checked by default by find_package()...
```

Thanks for pointing this out. The tarballs we ship on packages.seqan.de now install into `/usr/share/cmake/seqan/seqan-config.cmake` which is searched, but the Debian/Ubuntu package still installs in the wrong directory. I will try to get this fixed!

**Comment by wtwhite** [comment]
I just realised that my claim to have found the problem was wrong!  Clock skew has nothing to do with it.  Sorry for the confusion...

That is: I **can** reproduce the link error with the MWE even on a local filesystem where there is no clock skew.  (My mistake was that I forgot to undo the change to line 310 of `seqan-config.cmake` before trying to build...)  So the underlying cause of the link error remains unknown.  It can still be worked around using the change to line 310.

If there is a bright side to this, it's that clock skew appears to be harmless.  I had not thought too carefully about the "clock skew can confuse make" statements I'd heard, but then I realised that clock skew *shouldn't* actually break anything, since nothing in a build process *should* involve comparing file modification times to the current time -- only to other file modification times.  It's reassuring to me that a thing that shouldn't break stuff actually doesn't break stuff...  :-/

> P.S: regarding your comment inside the file

I'd forgotten about that, glad it was helpful!
